# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sam Dods
email: 
description:  Hi! 👋 My name is Sam Dods. Welcome to my quiet little corner of the web!
              <br><br>

              I'm a Lead Engineer at <a href='https://kinandcarta.com/create'>Kin + Carta Create</a>, specialising in iOS development and all things Mobile.
              <br><br>

              In 2018 I started writing new blog content on <a href='https://medium.com/@sdods'>Medium</a>, so that's where you'll find my latest technical articles. My <a href='archive'>archived posts</a> are still available.
              <br><br>



baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sam.dods.co" # the base hostname & protocol for your site
twitter_username: samdodz
github_username:  samdods
medium_url: https://medium.com/@sdods

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

